name: Build Release ZIP

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ZIP file
        run: |
          PLUGIN_SLUG="taphoai-gateway-qrcode-bank-transfer-for-woocommerce"
          mkdir $PLUGIN_SLUG
          
          # Copy all files to the temporary directory, excluding hidden files
          rsync -rc --exclude='.*' --exclude='$PLUGIN_SLUG' ./ $PLUGIN_SLUG/
          
          # Zip the directory
          zip -r taphoai-gateway.zip $PLUGIN_SLUG
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: taphoai-gateway-zip
          path: taphoai-gateway.zip

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: taphoai-gateway.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
